#
#  Do not edit this file.  This file is generated from 
#  package.bld.  Any modifications to this file will be 
#  overwritten whenever makefiles are re-generated.
#

unexport MAKEFILE_LIST
override PKGDIR = ti/sdo/codecs/aes
XDCINCS = -I. -I$(strip $(subst ;, -I,$(subst $(space),\$(space),$(XPKGPATH))))
XDCCFGDIR = package/cfg/

#
# The following dependencies ensure package.mak is rebuilt
# in the event that some included BOM script changes.
#
ifneq (clean,$(MAKECMDGOALS))
D:/CCS_3.3/xdctools_3_10_02/packages/xdc/bld/Utils.xs:
package.mak: D:/CCS_3.3/xdctools_3_10_02/packages/xdc/bld/Utils.xs
D:/CCS_3.3/xdctools_3_10_02/packages/xdc/services/spec/package/xdc.services.spec.sch:
package.mak: D:/CCS_3.3/xdctools_3_10_02/packages/xdc/services/spec/package/xdc.services.spec.sch
D:/CCS_3.3/xdctools_3_10_02/packages/xdc/bld/package/xdc.bld.sch:
package.mak: D:/CCS_3.3/xdctools_3_10_02/packages/xdc/bld/package/xdc.bld.sch
D:/CCS_3.3/xdctools_3_10_02/packages/xdc/IPackage.xs:
package.mak: D:/CCS_3.3/xdctools_3_10_02/packages/xdc/IPackage.xs
D:/CCS_3.3/xdctools_3_10_02/packages/xdc/package/xdc.sch:
package.mak: D:/CCS_3.3/xdctools_3_10_02/packages/xdc/package/xdc.sch
D:/CCS_3.3/xdctools_3_10_02/packages/xdc/bld/PackageContents.xs:
package.mak: D:/CCS_3.3/xdctools_3_10_02/packages/xdc/bld/PackageContents.xs
D:/CCS_3.3/xdctools_3_10_02/packages/xdc/services/global/Clock.xs:
package.mak: D:/CCS_3.3/xdctools_3_10_02/packages/xdc/services/global/Clock.xs
D:/CCS_3.3/xdctools_3_10_02/packages/xdc/bld/ITarget.xs:
package.mak: D:/CCS_3.3/xdctools_3_10_02/packages/xdc/bld/ITarget.xs
D:/CCS_3.3/xdctools_3_10_02/packages/xdc/corevers/package/xdc.corevers.sch:
package.mak: D:/CCS_3.3/xdctools_3_10_02/packages/xdc/corevers/package/xdc.corevers.sch
D:/CCS_3.3/xdctools_3_10_02/packages/xdc/bld/Library.xs:
package.mak: D:/CCS_3.3/xdctools_3_10_02/packages/xdc/bld/Library.xs
D:/CCS_3.3/xdctools_3_10_02/packages/xdc/bld/_gen.xs:
package.mak: D:/CCS_3.3/xdctools_3_10_02/packages/xdc/bld/_gen.xs
D:/CCS_3.3/xdctools_3_10_02/packages/xdc/xmlgen2.xs:
package.mak: D:/CCS_3.3/xdctools_3_10_02/packages/xdc/xmlgen2.xs
D:/CCS_3.3/xdctools_3_10_02/packages/xdc/services/global/package/xdc.services.global.sch:
package.mak: D:/CCS_3.3/xdctools_3_10_02/packages/xdc/services/global/package/xdc.services.global.sch
D:/CCS_3.3/xdctools_3_10_02/packages/xdc/package.xs:
package.mak: D:/CCS_3.3/xdctools_3_10_02/packages/xdc/package.xs
D:/CCS_3.3/xdctools_3_10_02/packages/xdc/recap.xs:
package.mak: D:/CCS_3.3/xdctools_3_10_02/packages/xdc/recap.xs
D:/CCS_3.3/xdctools_3_10_02/packages/xdc/bld/Script.xs:
package.mak: D:/CCS_3.3/xdctools_3_10_02/packages/xdc/bld/Script.xs
D:/CCS_3.3/xdctools_3_10_02/packages/xdc/xmlgen.xs:
package.mak: D:/CCS_3.3/xdctools_3_10_02/packages/xdc/xmlgen.xs
D:/CCS_3.3/xdctools_3_10_02/packages/xdc/bld/Executable.xs:
package.mak: D:/CCS_3.3/xdctools_3_10_02/packages/xdc/bld/Executable.xs
D:/CCS_3.3/xdctools_3_10_02/include/utils.tci:
package.mak: D:/CCS_3.3/xdctools_3_10_02/include/utils.tci
D:/CCS_3.3/xdctools_3_10_02/packages/xdc/shelf/package/xdc.shelf.sch:
package.mak: D:/CCS_3.3/xdctools_3_10_02/packages/xdc/shelf/package/xdc.shelf.sch
D:/CCS_3.3/xdctools_3_10_02/packages/xdc/bld/BuildEnvironment.xs:
package.mak: D:/CCS_3.3/xdctools_3_10_02/packages/xdc/bld/BuildEnvironment.xs
D:/CCS_3.3/xdctools_3_10_02/etc/config.bld:
package.mak: D:/CCS_3.3/xdctools_3_10_02/etc/config.bld
D:/CCS_3.3/xdctools_3_10_02/packages/xdc/services/intern/gen/package/xdc.services.intern.gen.sch:
package.mak: D:/CCS_3.3/xdctools_3_10_02/packages/xdc/services/intern/gen/package/xdc.services.intern.gen.sch
package.mak: package.bld
D:/CCS_3.3/xdctools_3_10_02/packages/xdc/xdc.tci:
package.mak: D:/CCS_3.3/xdctools_3_10_02/packages/xdc/xdc.tci
D:/CCS_3.3/xdctools_3_10_02/packages/xdc/bld/ITargetFilter.xs:
package.mak: D:/CCS_3.3/xdctools_3_10_02/packages/xdc/bld/ITargetFilter.xs
D:/CCS_3.3/xdctools_3_10_02/packages/xdc/om2.xs:
package.mak: D:/CCS_3.3/xdctools_3_10_02/packages/xdc/om2.xs
D:/CCS_3.3/xdctools_3_10_02/packages/xdc/bld/package.xs:
package.mak: D:/CCS_3.3/xdctools_3_10_02/packages/xdc/bld/package.xs
D:/CCS_3.3/xdctools_3_10_02/packages/xdc/bld/Repository.xs:
package.mak: D:/CCS_3.3/xdctools_3_10_02/packages/xdc/bld/Repository.xs
D:/CCS_3.3/xdctools_3_10_02/packages/xdc/template.xs:
package.mak: D:/CCS_3.3/xdctools_3_10_02/packages/xdc/template.xs
D:/CCS_3.3/xdctools_3_10_02/packages/xdc/services/intern/cmd/package/xdc.services.intern.cmd.sch:
package.mak: D:/CCS_3.3/xdctools_3_10_02/packages/xdc/services/intern/cmd/package/xdc.services.intern.cmd.sch
D:/CCS_3.3/xdctools_3_10_02/packages/xdc/services/intern/xsr/package/xdc.services.intern.xsr.sch:
package.mak: D:/CCS_3.3/xdctools_3_10_02/packages/xdc/services/intern/xsr/package/xdc.services.intern.xsr.sch
endif


all: .executables 
.executables: .libraries .dlls
.libraries: .interfaces

PKGCFGS := $(wildcard package.xs) package/build.cfg
.interfaces: package/package.xdc.inc package/package.defs.h package.xdc $(PKGCFGS)

-include package/package.xdc.dep
package/%.xdc.inc package/%_ti.sdo.codecs.aes.c package/%.defs.h: %.xdc $(PKGCFGS)
	@$(MSG) generating interfaces for package ti.sdo.codecs.aes" (because $@ is older than $(firstword $?))" ...
	$(XSRUN) -f xdc/services/intern/cmd/build.xs $(MK_IDLOPTS) -m package/package.xdc.dep -i package/package.xdc.inc package.xdc

ifneq (clean,$(MAKECMDGOALS))
-include package/package.cfg.dep
endif

package/package.ext.xml: package/package.cfg.xdc.inc
package/package.cfg.xdc.inc: $(XDCROOT)/packages/xdc/cfg/cfginc.js package.xdc
	@$(MSG) generating schema include file list ...
	$(CONFIG) -f $(XDCROOT)/packages/xdc/cfg/cfginc.js ti.sdo.codecs.aes $@

test:;
%,copy:
	@$(if $<,,$(MSG) don\'t know how to build $*; exit 1)
	@$(MSG) cp $< $@
	$(RM) $@
	$(CP) $< $@

$(XDCCFGDIR)%.c $(XDCCFGDIR)%.h $(XDCCFGDIR)%.xdl: $(XDCCFGDIR)%.cfg .interfaces $(XDCROOT)/packages/xdc/cfg/Main.xs
	@$(MSG) "configuring $(_PROG_NAME) from $< ..."
	$(CONFIG) $(_PROG_XSOPTS) xdc.cfg $(_PROG_NAME) $(XDCCFGDIR)$*.cfg $(XDCCFGDIR)$*

.PHONY: release,ti_sdo_codecs_aes
ti_sdo_codecs_aes.tar: package/build.cfg
ti_sdo_codecs_aes.tar: package/package.cfg.xdc.inc
ti_sdo_codecs_aes.tar: package/package.ext.xml
ti_sdo_codecs_aes.tar: package/package.xdc.inc
ti_sdo_codecs_aes.tar: package/package.bld.xml
ti_sdo_codecs_aes.tar: package/package.rel.dot
ifneq (clean,$(MAKECMDGOALS))
-include package/rel/ti_sdo_codecs_aes.tar.dep
endif
package/rel/ti_sdo_codecs_aes/ti/sdo/codecs/aes/package/package.rel.xml:

ti_sdo_codecs_aes.tar: package/rel/ti_sdo_codecs_aes.xdc.inc package/rel/ti_sdo_codecs_aes/ti/sdo/codecs/aes/package/package.rel.xml
	@$(MSG) making release file $@ "(because of $(firstword $?))" ...
	-$(RM) $@
	$(call MKRELTAR,package/rel/ti_sdo_codecs_aes.xdc.inc,package/rel/ti_sdo_codecs_aes.tar.dep)


release release,ti_sdo_codecs_aes: all ti_sdo_codecs_aes.tar
clean:: .clean
	-$(RM) ti_sdo_codecs_aes.tar
	-$(RM) package/rel/ti_sdo_codecs_aes.xdc.inc
	-$(RM) package/rel/ti_sdo_codecs_aes.tar.dep

clean:: .clean
	-$(RM) .libraries .libraries,*
clean:: 
	-$(RM) .dlls .dlls,*
#
# The following clean rule removes user specified
# generated files or directories.
#

ifneq (clean,$(MAKECMDGOALS))
ifeq (,$(wildcard package))
    $(shell $(MKDIR) package)
endif
ifeq (,$(wildcard package/external))
    $(shell $(MKDIR) package/external)
endif
ifeq (,$(wildcard package/lib))
    $(shell $(MKDIR) package/lib)
endif
ifeq (,$(wildcard package/rel))
    $(shell $(MKDIR) package/rel)
endif
ifeq (,$(wildcard package/cfg))
    $(shell $(MKDIR) package/cfg)
endif
ifeq (,$(wildcard package/internal))
    $(shell $(MKDIR) package/internal)
endif
endif
clean::
	-$(RMDIR) package


