/* onvifServerLib.c
   Generated by gSOAP 2.8.0 from onvif.h
   Copyright(C) 2000-2010, Robert van Engelen, Genivia Inc. All Rights Reserved.
   The generated code is released under one of the following licenses:
   GPL, the gSOAP public license, or Genivia's license for commercial use.
*/

/** Use this file in your project build instead of the two files onvifC.c and onvifServer.c. This hides the serializer functions and avoids linking problems when linking multiple clients and servers. */

#ifndef WITH_NOGLOBAL
#define WITH_NOGLOBAL
#endif
#define SOAP_FMAC3 static
#include "onvifC.c"
#include "onvifServer.c"

/* End of onvifServerLib.c */
